apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
  labels:
    app: notifications-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      automountServiceAccountToken: false
      containers:
        - name: notifications-api
          image: ghcr.io/sampaiobrenner/fcg-notifications-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: notifications-api-config
            - secretRef:
                name: notifications-api-secret
          startupProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: 5
            failureThreshold: 24
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
              ephemeral-storage: 256Mi
